### ISSUE TITLE
Search opens the homepage

### ISSUE THREAD

**Issue by itscool900** [libredirect/browser_extension#987] opened 2024-08-31 19:08 UTC
Searching with the LibRedirect search (set to SearXNG) sometimes opens the homepage instead of the query typed in. The only instances I remember that do this is https://search.rowie.at, https://searx.mv-software.de/, and https://search.gcomm.ch.

**Comment by qrhfz** [comment] 2024-09-03 10:03
the weird thing is that when it happens and i try to repeat it by only activating the instance, it works correctly the second time.

**Comment by ManeraKai** [comment] 2024-09-03 10:30
I think this is a duplicate of https://github.com/libredirect/browser_extension/issues/880.

**Comment by itscool900** [comment] 2024-09-08 15:06
Yes, it is. How do I redirect this to that? Should I just close with comment 'duplicate of #880'?

**Comment by ManeraKai** [comment] 2024-09-29 20:52
> Yes, it is. How do I redirect this to that? Should I just close with comment 'duplicate of https://github.com/libredirect/browser_extension/issues/880'?

Yes, close this as a duplicate.

> Also, is there a way to re open the issue?

Not in GitHub. You can in Codeberg though.

**Closed** 2024-09-29 20:53 UTC
Labels: duplicate
