### ISSUE TITLE
Add speedtest to Librespeed

### ISSUE THREAD

**Issue by sonalder-darlene** [libredirect/browser_extension#170] opened 2022-04-05 21:48 UTC
A way to redirect [Speedtest](https://www.speedtest.net/) (and other similar website if anybody knows some) to [LibreSpeed](https://librespeed.org/) instances. it would be nice

**Comment by ManeraKai** [comment] 2022-04-14 10:46
So just the home url `/`?

**Comment by sonalder-darlene** [comment] 2022-04-14 11:18
I think yes. I don't see any other usecases for regular users.
Who needs Speedtest VPN ? I never used any of there stuff but idk

**Comment by ManeraKai** [comment] 2022-04-14 11:21
>  Who needs Speedtest VPN ? I never used any of there stuff but idk

I need it to test my internet speed ¯\\_(ツ)_/¯

**Comment by sonalder-darlene** [comment] 2022-04-14 11:24
I mean they also sell a VPN service because it''s trendy in the tech industry nowadays.

**Comment by ManeraKai** [comment] 2022-04-14 11:27
I see. I thought you mean just Speedtest not the VPN 👍

**Comment by ManeraKai** [comment] 2022-04-14 21:27
And we added it! If you face any issue, just write it here. I'll close it for now.

**Comment by ManeraKai** [comment] 2022-05-07 09:58
I'm thinking of removing LibreSpeed as it's only just redirecting one link and there's only one instance to make an automation for it.
Like if someone wants to use, just visit librespeed.org and you're good to go.

**Comment by EdwardLangdon** [comment] 2022-05-07 13:41
I think that you are good with removing it. As, Most will ocassionally use Speedtest.net not often. So, It's good to go.

For their Privacy if they forget to use Librespeed, Maybe we can set the extension to delete speedtest.net site's Cookies on exit or at startup.

**Comment by ManeraKai** [comment] 2022-05-07 14:23
> For their Privacy if they forget to use Librespeed, Maybe we can set the extension to delete speedtest.net site's Cookies on exit or at startup.

cookies are now not that important for fingerprinting.

If someone wants to test their internet speed, just visit: [librespeed.org/](https://librespeed.org/)

**Comment by EdwardLangdon** [comment] 2022-05-07 14:45
Indeed, But What if the majority of the People don't know about Librespeed ?

**Comment by ManeraKai** [comment] 2022-05-07 14:47
Then you tell them to use it just like how people started using [fastnet.com](https://fast.com/)

**Comment by EdwardLangdon** [comment] 2022-05-07 15:11
Do they ?

IDK.

**Comment by IronMaltese** [comment] 2022-05-07 15:20
I feel like most people just look up how fast is my internet, and click the first result

**Comment by pritkr** [comment] 2022-05-08 02:42
I think librespeed shouldn't be removed. It already chooses between different servers to test speed in the official instance which makes it trivial to have different instances. I think people use speedtest.net and fast.com out of memory and not from search engine as they would have used google's own speed test which appears when we google speed test. I even think libredirect should redirect fast.com to librespeed

**Comment by IronMaltese** [comment] 2022-05-08 02:53
> I think librespeed shouldn't be removed. It already chooses between different servers to test speed in the official instance which makes it trivial to have different instances. I think people use speedtest.net and fast.com out of memory and not from search engine as they would have used google's own speed test which appears when we google speed test. I even think libredirect should redirect fast.com to librespeed

Yeah I understood removing Pixiv, but removing Librespeed felt like a regression in features

**Comment by ManeraKai** [comment] 2022-05-08 07:04
> It already chooses between different servers to test speed in the official instance which makes it trivial to have different instance

And it's trivial too to be in LR as there's just no need for redirection. It's only one link that people should have in memory like they have speedtest.net and fast.com.

LR is a tool to automate hard redirections like browsing YouTube or redirecting iframes and images in a site. Using Librespeed is as easy as visiting [librespeed.org](https://librespeed.org). If you want Librespeed to get popular, then publish it on privacytools.io and other websites to get noticed.

Adding a new redirection adds a new regex therefore slows the visiting sites more. This should be kept in mind too.

**Comment by coffeebank** [comment] 2022-05-08 07:14
The list of services does seem to be getting pretty long.... I won't dispute or support any adding/removing of services but adding fully custom redirects for any site and/or a "More" section could be helpful

for now I've been using https://addons.mozilla.org/en-US/firefox/addon/redirector/ but it would be nice to have LR handle all redirects since it can also fetch/ping instances

**Comment by ManeraKai** [comment] 2022-05-08 07:43
![soju_discussion](https://user-images.githubusercontent.com/40805353/167286703-8f9670e8-58fa-4786-a849-37bacf455e75.png)

**Comment by ManeraKai** [comment] 2023-05-14 16:34
LibreSpeed will be re-added. Yes it's a single instance, but the argument "Exposing newbies to privacy sites as much and also as easy as possible" is a really good point.

**Comment by ManeraKai** [comment] 2023-05-14 16:35
isitup.org will also be added: https://github.com/libredirect/browser_extension/issues/658

**Closed** 2023-05-16 12:38 UTC
Labels: New Frontend
