### ISSUE TITLE
Add missing SafeTwitch redirect clips.twitch.tv

### ISSUE THREAD

**Issue by toyboatcash** [libredirect/browser_extension#891] opened 2024-01-26 17:05 UTC
https://clips.twitch.tv/ShyMoralTireKeepo-39wl_RLTgP9-4wNH to  https://safetwitch.datura.network/modderpaulscambaits/clip/ShyMoralTireKeepo-39wl_RLTgP9-4wNH

see https://codeberg.org/SafeTwitch/safetwitch/issues/46 for more info

**Comment by ManeraKai** [comment] 2024-01-28 13:43
Duplicate of https://github.com/libredirect/browser_extension/issues/833

**Closed by ManeraKai** 2024-01-28 13:43 UTC
