### ISSUE TITLE
Please add back Nitter again.

### ISSUE THREAD

**Issue by Giger22** [libredirect/browser_extension#902] opened 2024-03-12 12:26 UTC
Why did you remove nitter? https://nitter.poast.org still works

**Comment by NoPlagiarism** [comment] 2024-03-12 14:04
Nitter is removed due being unmaintained and [pronouncing dead by author themselve](https://github.com/zedeus/nitter/issues/1155#issuecomment-1913361757).

For self-hosted ([check this repo](https://github.com/sekai-soft/freebird)) and public instances that still work you can use [Redirector](https://einaregilsson.com/redirector). Hope with #892 all rules will be in one place somewhen

Also, issue can be kinda called duplicate of #898

**Closed** 2024-03-12 15:31 UTC

**Comment by MintMain21** [comment] 2024-03-13 18:57
I'm glad at least one instance still works, but there's no guarantee it'll last long anyway.

**Comment by githubtefo** [comment] 2024-03-14 01:08
Please just keep it active until https://nitter.poast.org will stop working.

**Comment by mirh** [comment] 2024-03-15 22:24
There are also a [few other](https://github.com/zedeus/nitter/wiki/Instances) instances still up
My 2c are to use [version 2.8.1](https://addons.mozilla.org/firefox/addon/libredirect/versions/) and disable automatic updates (surprisingly it was hard to find many such addons that actually had x.com actually being redirected too)

**Comment by Giger22** [comment] 2024-03-17 09:07
Disappointing.

**Comment by githubtefo** [comment] 2024-03-17 17:02
> There are also a [few other](https://github.com/zedeus/nitter/wiki/Instances) instances still up My 2c are to use [version 2.8.1](https://addons.mozilla.org/firefox/addon/libredirect/versions/) and disable automatic updates (surprisingly it was hard to find many such addons that actually had x.com actually being redirected too)

OK, I will do that for a while. Hope to remember switching back if this is reverted. Thanks!

**Comment by 6Fv** [comment] 2024-03-30 18:58
If you insist on removing Twitter, consider adding a "Custom" option. URL matching rules should be configurable in the "custom" option. This way people who still use Nitter, or other sites, can continue to do so. Additionally, this repo won't get blown up with issues.

**Leave it up to the *user*...**

**Comment by NoPlagiarism** [comment] 2024-03-30 19:12
> URL matching rules should be configurable in the "custom" option

That's what [Redirector](https://einaregilsson.com/redirector) is for

This will be solved with #892

**Comment by githubtefo** [comment] 2024-04-02 17:39
Redirector works for me with these two redirects:

Nitter from twitter
Redirect:

https://twitter.com/*
to:

https://nitter.poast.org/$1
Hint:

    to $1
    Example:

https://twitter.com/x → https://nitter.poast.org/x
Applies to:

Main window (address bar)
twitter from X
Redirect:

https://x.com/*
to:

twitter.com/$1
Hint:

    to $1
    Example:

https://x.com/x → twitter.com/x
Applies to:

Main window (address bar)

Another addon to my list 🙄

**Comment by MintMain21** [comment] 2024-04-30 21:43
> Please just keep it active until https://nitter.poast.org will stop working.

Aaaand it's dead. 

I hope that month and a half was worth it.

**Comment by mirh** [comment] 2024-05-01 12:16
It does still work happily

EDIT: https://github.com/libredirect/browser_extension/issues/934

**Comment by Jaspix** [comment] 2024-06-11 02:33
People still maintain private instances, kind of a dumb move to remove a feature that was already there.

**Comment by Giger22** [comment] 2024-06-11 10:13
Ok, I [forked it](https://github.com/Giger22/browser_extension_nitter_fix/releases/tag/2.8.4-3)! Very simple just added removed commits... Shame you do not want it add back in.

**Comment by Jaspix** [comment] 2024-06-11 21:10
> Ok, I [forked it](https://github.com/Giger22/browser_extension_nitter_fix/releases/tag/v2.8.4-4)! Very simple! I've just added removed commits... Shame you do not want it add back in. Maybe you can just rethink it...

based

**Comment by YAKSL** [comment] 2024-06-15 05:09
> Ok, I [forked it](https://github.com/Giger22/browser_extension_nitter_fix/releases/tag/v2.8.4-4)! Very simple! I've just added removed commits... Shame you do not want it add back in. Maybe you can just rethink it...

THANK YOU
