### ISSUE TITLE
setting https://cal1.iv.ggtyler.dev as instance for inv redirects to homepage instead

### ISSUE THREAD

**Issue by rezad1393** [libredirect/browser_extension#997] opened 2024-09-16 12:45 UTC
setting https://cal1.iv.ggtyler.dev as instance for invidious and opening a youtube page redirects to homepage at https://cal1.iv.ggtyler.dev/feed/popular instead

**Comment by PricacyPro0** [comment] 2024-09-16 16:52
you can add this instance manually and it also doesn't seem to work for me

**Comment by ManeraKai** [comment] 2024-09-16 21:04
Duplicate of https://github.com/libredirect/browser_extension/issues/996

**Closed by ManeraKai** 2024-09-16 21:04 UTC
