### ISSUE TITLE
Feature request: "Use freetube over invidious/piped when possible" like with privacy redirect add-on

### ISSUE THREAD

**Issue by XxTriviumxX** [libredirect/browser_extension#734] opened 2023-06-09 19:36 UTC
~~This is an issue similar to what i posted earlier with invidious in mind. I remade it here with piped in mind because invidious will die soon.~~  @xbdm thanks for the precisions. 

Here's my feature request:
I want to migrate to libredirect from privacy redirect. The only thing holding me back is the "Use freetube over invidious when possible" function. If there is such function already, please show me how to do it.

The function works like this: It redirects everything it can to Freetube, and the impossible stuff (embedded stuff) gets processed with invidious / piped

edit: My current workaround is to disable youtube redirects on libredirect and enable youtube redirects to freetube/invidious on privacy redirect

Thanks :)

**Comment by xbdmHQ** [comment] 2023-06-09 22:22
> This is an issue similar to what i posted earlier with invidious in mind. I remade it here with piped in mind because invidious will die soon.
> 
> Here's my feature request: I want to migrate to libredirect from privacy redirect. The only thing holding me back is the "Use freetube over ~invidious~ piped when possible" function. If there is such function already, please show me how to do it.
> 
> The function works like this: It redirects everything it can to Freetube, and the impossible stuff (embedded stuff) gets processed with ~invidious~ piped instead.
> 
> Thanks :)

Invidious will not die soon, The owners has transfered over to own dmca ignored gitea instance and it is still will be maintained. The source is open-source, and there will still be people maintain it. Including me, Check out my invidious instance: https://yt.whateveritworks.org

**Comment by XxTriviumxX** [comment] 2023-06-09 22:29
i thought it was crumbling apart because invidious enbedded video did not work for hours and started to work very recently. That included ALL instances.

**Comment by ManeraKai** [comment] 2023-06-09 22:54
Duplicate of: https://github.com/libredirect/browser_extension/issues/624

**Closed** 2023-06-10 01:18 UTC
