### ISSUE TITLE
Add NerdsforNerds (GeeksforGeeks Frontend)

### ISSUE THREAD

**Issue by toyboatcash** [libredirect/browser_extension#982] opened 2024-08-24 21:40 UTC
Source Code: https://git.vern.cc/cobra/NerdsforNerds

Known instances list: https://git.vern.cc/cobra/NerdsforNerds/raw/branch/main/instances.json

Known instances clearnet https://nn.vern.cc, tor http://nn.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion, i2p http://verndxuxy2gxwbghph2exffcx32d3estsfy4k7tkyrvhhac4ai4a.b32.i2p

For: https://www.geeksforgeeks.org

Example https://www.geeksforgeeks.org/script-command-in-linux-with-examples/

becomes https://nn.vern.cc/script-command-in-linux-with-examples/

**Comment by ManeraKai** [comment] 2024-08-25 15:27
Duplicate of https://codeberg.org/LibRedirect/browser_extension/issues/148

**Closed by ManeraKai** 2024-08-25 15:27 UTC
