### ISSUE TITLE
Twitter/X redirection doesn't work

### ISSUE THREAD

**Issue by SamantazFox** [libredirect/browser_extension#917] opened 2024-04-18 20:25 UTC
If I click on a twitter link, I'm not redirected to Nitter anymore. My browser auto-updated the extension, so I guess this is intentional as Nitter is now completely useless without an account?

In all cases, I don't like the unexpected change. I'd have preferred the original domain to be blocked and getting some warning of sorts, not being redirected to the original without a hint why the extension failed at its job.

**Comment by NoPlagiarism** [comment] 2024-04-19 04:32
Duplicate of #902 and #898

Read discussion there

**Comment by mpeter50** [comment] 2024-04-19 21:08
It's such a shame that even after leaving google play and such garbage distribution platforms behind me, disabling automatic updates its still regularly validated by various software projects issuing downgrades.
I _always_ have to keep in mind to not update Libredirect ever again. It has happened 2 or 3 times already, but I somehow come to terms with it and updated. Not sure if that will happen once more.

Nitter is working. Here is proof:

![image](https://github.com/libredirect/browser_extension/assets/83356418/c7112d6c-c8c0-44fe-81c1-1696af45bfc0)

**Comment by user451421541757324** [comment] 2024-04-20 10:01
> Nitter is working

What is the name of the instance?

**Comment by mpeter50** [comment] 2024-04-20 13:33
Sorry, forgot to include that. It was nitter.privacydev.net .

~~At the moment it is rate limited, but thats normal by the past x years.~~
But not even. Just before sending in this comment, I reloaded the page, and now it has loaded properly:

![image](https://github.com/libredirect/browser_extension/assets/83356418/af1e27f3-11b9-45dd-a24e-cbfd05e2f365)

Here is the exact URL of the post thats on the screenshots: https://nitter.privacydev.net/pinguinfighter/status/1781060206845104636#m

**Comment by ManeraKai** [comment] 2024-04-20 14:28
https://github.com/libredirect/browser_extension/issues/892#issuecomment-1993344395

**Closed by ManeraKai** 2024-04-20 14:28 UTC

**Comment by Giger22** [comment] 2024-06-11 10:17
Ok, I [forked it](https://github.com/Giger22/browser_extension_nitter_fix/releases/tag/2.8.4-3)! Very simple! I've just added removed commits... Shame you do not want it add back in.

**Comment by mpeter50** [comment] 2024-06-11 12:44
By the way, certain forks of Nitter still work. Sadly its often rate limited, but somehow my RSS reader always manages to get hold of new posts in a reasonable amount of time, even though its only set up to sync every single day.
