### ISSUE TITLE
Error in event handle v.2.8.3

### ISSUE THREAD

**Issue by WoefulWrecker** [libredirect/browser_extension#912] opened 2024-03-23 03:42 UTC
Brave is up to date
[Version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (x86_64)](https://brave.com/latest/)

LibRedirect : 2.8.3

![1 browser_specific_settings](https://github.com/libredirect/browser_extension/assets/54433630/3b24813e-87af-44f3-a220-6aa3c80e1b43)
![2 exceptions](https://github.com/libredirect/browser_extension/assets/54433630/bb19f7be-496a-41cd-bea2-63201441606f)
![3 redirectOnlyInIncognito](https://github.com/libredirect/browser_extension/assets/54433630/3b4bb846-8189-415f-ac64-0d2b309a2e05)

**Comment by ManeraKai** [comment] 2024-03-23 03:50
Duplicate of https://github.com/libredirect/browser_extension/issues/906

**Closed by ManeraKai** 2024-03-23 03:50 UTC
