### ISSUE TITLE
Add instance will delete path in url, causing wrong redirection.

### ISSUE THREAD

**Issue by TaivasJumala** [libredirect/browser_extension#889] opened 2024-01-25 20:49 UTC
Libredirect 2.8.1
Firefox 121.0
bilibili

reproduce:
1. add instance https://moeyy.cn/mikuinvidious/
2. reports error

what happen here:
it just add https://moeyy.cn/ not https://moeyy.cn/mikuinvidious/
which caused error.

So link like https://www.bilibili.com/video/av2 should be redirect to https://moeyy.cn/mikuinvidious/video/av2 not https://moeyy.cn/video/av2

besides, https://mikuinv-gs.vern.cc/ seems to be no long supported

**Comment by ManeraKai** [comment] 2024-01-28 12:35
Duplicate of https://github.com/libredirect/browser_extension/issues/875

**Closed by ManeraKai** 2024-01-28 12:35 UTC
