### ISSUE TITLE
New 3.0.0 error message incorrectly detects bot protection on xcancel.com as instance being unavailable

### ISSUE THREAD

**Issue by 0n-s** [libredirect/browser_extension#993] opened 2024-09-14 09:14 UTC
The bot vetting on xcancel.com gives an HTTP 503 in its second stage, which makes LibRedirect give up on it even though it's completely functional.

**Comment by Rascalov** [comment] 2024-09-14 10:08
For now I downgraded to 2.9.1 (Brave)
It's a cool idea, https://github.com/libredirect/browser_extension/commit/1492345b0d2f0f4d6d4a7a6f8814596785a472b0 and tbh I don't blame them for not creating a toggle for this feature since I wouldn't expect xcancel to throw a 503 during bot vetting.

**Comment by ManeraKai** [comment] 2024-09-14 19:52
Duplicate of https://github.com/libredirect/browser_extension/issues/992

**Closed by ManeraKai** 2024-09-14 19:52 UTC
