### ISSUE TITLE
Add instance button removes ping values

### ISSUE THREAD

**Issue by IntinteDAO** [libredirect/browser_extension#792] opened 2023-08-03 08:43 UTC
LibRedirect 2.7.1
Firefox 115.0.2esr

I don't know if this is intentional, in my opinion a mistake.

If we ping the instances to see if they exist
And then try to add / remove them

Then the ping value disappears. Which in my opinion is wrong, because I always tried to select services according to whether they exist. 

Screens:

**Ok, let's check instances - please ping all**
![obraz](https://github.com/libredirect/browser_extension/assets/56807194/e7091621-17b5-4a90-80fc-0c402cfeff79)

**Oh, instances doesn't work (some), let's delete them**
![obraz](https://github.com/libredirect/browser_extension/assets/56807194/016476f3-b8d2-4f4d-a362-17b1003c455e)

**Where is my ping now?**
![obraz](https://github.com/libredirect/browser_extension/assets/56807194/ae6cd2ca-e8c3-4621-893e-c0cc02064d58)

**Comment by ManeraKai** [comment] 2023-08-03 08:51
Duplicate of https://github.com/libredirect/browser_extension/issues/773

**Closed by ManeraKai** 2023-08-03 08:51 UTC
