### ISSUE TITLE
Make settings page responsive/adaptive

### ISSUE THREAD

**Issue by nonremittal** [libredirect/browser_extension#811] opened 2023-09-01 14:32 UTC
When resizing the settings window it would be great if the page adapted to a narrower window: single column, stacked buttons, and so on.  Anyone savvy with CSS?

As an aside, this means the extension would become a lot more user-friendly on versions of Firefox for Android that support [custom extensions](https://support.mozilla.org/en-US/kb/extended-add-support) 😉 (the extension itself behaves pretty much the same as desktop already).

**Comment by ManeraKai** [comment] 2023-09-02 08:56
When custom extensions are supported in normal Fenix, I'll improve the responsiveness more, for now, this issue is a duplicate of https://github.com/libredirect/browser_extension/issues/748.

**Closed** 2023-09-02 08:56 UTC
