### ISSUE TITLE
libreddit and nitter redirects no longer work on firefox 115.0.2 (linux)

### ISSUE THREAD

**Issue by XxTriviumxX** [libredirect/browser_extension#772] opened 2023-07-23 14:48 UTC
system: arch linux KDE Plasma
browser: firefox 115.0.2

Everything works great with Brave browser.

Behavior with firefox 115.0.2: Goes straight to reddit / twitter. Piped redirections do work, however.

note: I have privacy redirect installed on firefox because i'm still waiting to get the "use freetube over invidious/piped when possible" function. 

Things i tried: removed libredirect + rebooted +reinstalled libredirect, then manually set it back up one redirect at a time. Disabled my vpn. Removed privacy redirect.
Things im willing to try: fiddle in firefox's settings. Use a beta version if a fix is provided with it.
Things i will not try:  i will not re-install firefox. I will not re-install arch linux.

**Comment by jahtnamas** [comment] 2023-07-24 19:04
this is also happening to me, minus having privacy redirect so that's likely not the issue... and absolutely no reddit redirection is occurring (i use teddit). possible that they were internally disabled without being removed due to both these platforms being Difficult Lately?

**Comment by XxTriviumxX** [comment] 2023-07-24 22:13
most likely the new libredirect version has regression.

**Comment by ManeraKai** [comment] 2023-07-26 22:02
Try this zip: [libredirect-2.7.1.zip](https://github.com/libredirect/browser_extension/files/12136156/libredirect-2.7.1.zip)

**Comment by ManeraKai** [comment] 2023-07-27 08:35
Duplicate of: https://github.com/libredirect/browser_extension/issues/765

**Closed by ManeraKai** 2023-07-27 08:35 UTC

**Comment by XxTriviumxX** [comment] 2023-07-27 13:50
got fixed in the zip file version.
