### ISSUE TITLE
Unwanted forward slash being added to custom Redlib URLs

### ISSUE THREAD

**Issue by AresUII** [libredirect/browser_extension#999] opened 2024-09-20 21:22 UTC
Steps to reproduce:

1. Go to Settings > Services.
2. Select Service > Reddit.
3. Under "Add your favorite instances", type exactly "https://lr.eu.psf.lt".

What I wanted to happen:
"https://lr.eu.psf.lt" [with *no* terminal slash] gets added to the list of selected instances

What LibRedirect did:
"https://lr.eu.psf.lt/" [with a terminal slash that *I did not type*] got added instead, as shown:
![image](https://github.com/user-attachments/assets/afac536e-03d9-45cb-9d61-8cccff0308f7)

The knock-on effect:
Redirects go to pages with a *double slash*, e.g. "https://lr.eu.psf.lt//" for the frontpage; this is incorrect and breaks some other services, like Invidious

**Comment by ManeraKai** [comment] 2024-09-20 21:57
Duplicate of https://github.com/libredirect/browser_extension/issues/996

I will release soon.

**Closed by ManeraKai** 2024-09-20 21:57 UTC
