### ISSUE TITLE
Feature Request: Support Managed Storage

### ISSUE THREAD

**Issue by linsui** [libredirect/browser_extension#645] opened 2023-03-05 15:37 UTC
This is for the same usage as https://github.com/libredirect/libredirect/issues/628:

> Since the latency test and instance update are removed in recent versions, I feel that it's very difficult to maintain the large list manully.

With this the users can config the list with a config file and sync it easily.

Documents:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#managed_storage_manifests

uBlock Origin docs for example:
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

Thanks!

**Comment by IkelAtomig** [comment] 2023-03-06 02:53
You want a synced settings setup similar to uBlock Origin's ?

Latency test is being re-added, btw.

**Comment by IkelAtomig** [comment] 2023-03-06 02:58
Kinda duplicate of #576

**Comment by linsui** [comment] 2023-03-06 04:16
> But this would be only for Firefox. So, What about Chromium users. We need to think of them too.

Chrome also supports managed storage but has a little difference. See https://github.com/gorhill/uBlock/blob/2e6cc8a36a35c1893cf2151340216c4920995028/platform/chromium/webext.js#L136.

> Latency test is being re-added, btw.

But according to https://github.com/libredirect/libredirect/issues/628#issuecomment-1425538808 I still need to manage the list manully.

> Kinda duplicate of https://github.com/libredirect/libredirect/issues/576

But the sync storage can't be managed out of the the browser.

I tried the function of uBO and I found that it's very convenient to manage the settings with a json file. I can also do some automation, e.g. enabling scripts on all nitter instances so that when libredirect redirects to a random instance I don't need to enable the scripte on it manully.

**Comment by ManeraKai** [comment] 2023-03-11 04:55
It's nice but way out of scope for LibRedirect. LibRedirect isn't meant to be that much advanced, it's meant to be simple. I will improve the instances list https://github.com/libredirect/libredirect/issues/643 though.

**Comment by linsui** [comment] 2023-03-11 05:50
I thought reading config from managed storage doesn't make it complicated. Will a PR for this be accepted?

**Comment by ManeraKai** [comment] 2023-03-11 05:58
It will make the code more complicated in every single part where is uses storage. It's a really niche setup so little people will use it.

**Comment by linsui** [comment] 2023-03-11 06:45
I thought we can read the managed storage in https://github.com/libredirect/libredirect/blob/master/src/pages/background/background.js. If there is managed storage, the loal storage will be overrided. The behavior is similiar to importing the setting. So it's only read when the extension is initialized. The options changed from the UI will be kept until the browser is closed.

**Comment by ManeraKai** [comment] 2023-05-25 05:22
I don't think this will be implemented. I'm closing the issue.

**Closed by ManeraKai** 2023-05-25 05:22 UTC
Labels: enhancement
