### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by trymeouteh** [libredirect/browser_extension#75] opened 2022-02-28 17:50 UTC
If possible could this extension be modified to work on Android firefox based browser and Android chromium browsers.

**Comment by ManeraKai** [comment] 2022-02-28 17:54
I'll see

**Comment by catwithbanana** [comment] 2022-03-01 18:37
The extension works just fine if you use Firefox Nightly or a fork like Mull, which allow loading non-curated extensions. The set-up is more annoying than it should be (thanks Mozilla) but everything functions as expected.

**Comment by ManeraKai** [comment] 2022-03-01 19:32
I can publish it for android too. The only thing I'm concerning with is the interface.

**Comment by ManeraKai** [comment] 2022-03-10 07:39
Seems Firefox doesn't allow any extensions other than the ones that it recommends. They're 17 only. So the extension needs to be reviewed and recommended by Firefox staff to show up.

**Comment by linsui** [comment] 2022-03-30 07:41
The extension has a small problem on Android that the setting page is opened but I'm still on the previous page.

**Comment by ManeraKai** [comment] 2022-03-30 15:48
How is that?

**Comment by linsui** [comment] 2022-03-30 16:01
uBlock Origin's example: https://github.com/gorhill/uBlock/blob/0c7318d6f749ef852c36c76e278048816c2f2f8c/src/popup.html#L23 I guess the `target` attribute is important.

**Comment by ManeraKai** [comment] 2022-03-30 16:03
So you need to open it in a new tab when you click on the `Settings` button right?

**Comment by linsui** [comment] 2022-03-30 16:07
I  hope that I'm brought to the opened tab when I click on the Settings. On Android the tab is opened but I'm left on the popup page.

**Comment by ManeraKai** [comment] 2022-03-30 16:08
I see now. So it opens on a new tab but not focused to it.

**Comment by linsui** [comment] 2022-03-30 16:14
Yes. On Android it's annoying since I need to return to the origin page and switch to the new page.

**Comment by kartikdc** [comment] 2022-04-08 03:45
Can someone tell me how to install this extension on Firefox Android? I have been able to enable the debug menu to allow adding custom add-on collections but not sure if that is the right way to go about it.

**Comment by linsui** [comment] 2022-04-08 03:51
Since you have enabled custom add-on collections, you can add a collention containing this extension.

**Comment by ManeraKai** [comment] 2022-04-09 05:25
I think I should add those steps to the wiki.

**Comment by kartikdc** [comment] 2022-04-11 03:50
You can link this blog post in the README. The instructions here are clear enough and there are screenshots too.

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by ManeraKai** [comment] 2022-04-11 23:06
@austinhuang0131 remembered me that there is already a phone app called [UntrackMe](https://framagit.org/tom79/nitterizeme#privacy-friendly-front-ends): https://github.com/libredirect/libredirect/issues/184#issuecomment-1095253522. It's now mentioned in the README. I'll close the issue and won't add the blog to the wiki as I won't support Android. It's much easier to handle links using a system app rather than a browser when using phones.

**Comment by linsui** [comment] 2022-04-12 08:58
> This is needed so if you want to either copy the link rather than opening it in a browser. All your life isn't in the browser when using a mobile phone.

Oh, great, I just found that I can make Firefox always open the link in UntrackMe and UntrackMe always open the link in Firefox. It's not so seamless but works well enough.

> I agree. I suggest helping UntrackMe and making those settings available on it.

I don't know if it's possible to do that in an app though. Currently libredirect already has much richer features than UntrackMe for me. 

> This was true before, but a big problem came and we stopped using sync storage. We're no using local storage.

I can still export and import the settings which is better than tweak those settings manully on every device.

Additionally, it's much easier for me to help libredirect works well on Android than UntractMe.

**Comment by austinhuang0131** [comment] 2022-04-12 12:58
But can you do this in an app in a way more seamless than UntrackMe though? (For me I can open with UntrackMe with my default browser whenever I click any link from any non-browser app; in browser this only applies to frontend-able URLs.) Really the only things missing in it are auto updating instances and round robin which should not require reinventing the wheel. UntrackMe sends settings (Invidious) as a query string, I don't think it can modify cookies.

**Comment by ManeraKai** [comment] 2022-04-12 13:06
Many other frontends/services don't use url queries, many of them even remove them if you clicked another link in the site or got redirected. url queries isn't a reliable option.
I remember that typing https://invidious.kavin.rocks/?dark_mode=true will get your redirected to https://invidious.kavin.rocks/feed/popular and the queries are removed.

**Comment by ManeraKai** [comment] 2022-04-12 13:16
How is that?

**Comment by 0x6e656b6f** [comment] 2022-04-29 16:37
Can you add Newpipe? If you long tap a link, there's an "Open link in external app" option in Firefox. Maybe you could use that option to automatically redirect Youtube link to open in Newpipe.

**Comment by 0x6e656b6f** [comment] 2022-04-29 16:41
Also I tested the extension in Firefox Nightly, most stuff works but there's a crash when clicking on site settings. Here's some step to reproduce:
1. Addons > LibRedirect
2. Nightly opens LibRedirect settings in a mobile friendly UI.
3. Tap on "YouTube" or the icon to modify the YouTube settings.
4. Nightly crashed.

The crash however don't occur when you open the extension using moz-extension://extension-id URL (using that URL also opens the normal UI that don't look mobile friendly).

**Comment by ManeraKai** [comment] 2022-04-29 18:17
> Can you add Newpipe? If you long tap a link, there's an "Open link in external app" option in Firefox. Maybe you could use that option to automatically redirect Youtube link to open in Newpipe.

NewPipe should support this natively. I don't know if they do but I LibreTube has that.

**Comment by ManeraKai** [comment] 2022-04-29 18:18
> Nightly opens LibRedirect settings in a mobile friendly UI.

That's interesting, how does that look?

**Comment by 0x6e656b6f** [comment] 2022-04-30 01:41
> > Can you add Newpipe? If you long tap a link, there's an "Open link in external app" option in Firefox. Maybe you could use that option to automatically redirect Youtube link to open in Newpipe.
> 
> NewPipe should support this natively. I don't know if they do but I LibreTube has that.

That's only for YouTube link that's not in the web browser. But if you type youtube.com then press Enter in the browser search bar, then Newpipe won't open. Clicking YT URL from search engine result opens up Newpipe but also opens up YT tab and load the video there.

**Comment by 0x6e656b6f** [comment] 2022-04-30 02:01
> > Nightly opens LibRedirect settings in a mobile friendly UI.
> 
> That's interesting, how does that look?

![image](https://user-images.githubusercontent.com/97211491/166086241-7e61e1fd-e6ac-4905-ae73-a8b91d0bc522.png)

**Comment by Mrnofish** [comment] 2022-06-29 17:39
BTW while it does work on Android, the settings arent' working as nicely as expected, e.g. as well as uBlock Origin.

For instance, when I tap on Settings, the new Settings tab opens in the background, and it is necessary to tap the back button for it to show.

Additionally, since the menu is displayed on the left, most of the actual settings are outside of the viewport, and there is a ton of blank space between the controls on the right and the description on the left. In short, it's like it's assuming a display whose proportions are those of a regular PC monitor rather than the narrow/tall screen of a typical current smartphone.

**Comment by MintMain21** [comment] 2023-12-12 01:35
Update: Firefox officially supports extensions on Android now.

You'll have to update it on your end to mark it as Android compatible, let alone test it.

**Comment by Nitrousoxide** [comment] 2023-12-16 17:21
> Android support would be fantastic. Right now I have to open websites in new tabs via sharing links to UntrackMe, which modifies the URL and returns it to the browser. This extension would massively improve convenience (not to mention vastly increase the number of supported websites).

You can use `https://addons.mozilla.org/en-US/firefox/addon/redirector/` in the meantime as it's in the mobile extension repo though it is hardly ideal since you need to make your own redirection rules. 

Here's a simple redirector from twitter/x -> a nitter instance you can load into it and tweak.

https://gist.github.com/Nitrousoxide/7419625b6c7bf82a7ace080d60f739f5

Libredirect would be far superior though.

**Comment by Mrnofish** [comment] 2023-12-17 00:54
As suggested previously, LibRedirect has already been working on Android, just as long as it is added to a personal collection on AMO.

This feature is available on Firefox Beta/Nightly and Fennec, probably other forks that I've never used, too.

No need to jump through hoops or use outdated or more limited software.

**Comment by unchartedpopsicle** [comment] 2023-12-17 08:29
There is no need for that hoop, either. On the latest Firefox stable you can just open the add-on page in desktop mode and install directly.

**Comment by MintMain21** [comment] 2023-12-17 21:31
![image](https://github.com/libredirect/browser_extension/assets/91362684/35a16e2a-a571-4ec2-8791-d7454a5ec821)

Just add the "Android" badge plz.

**Comment by IkelAtomig** [comment] 2023-12-18 03:16
But don't be furious if it didn't work out well. Open a new issue titled as Problems in Android Version.

**Comment by ManeraKai** [comment] 2023-12-18 06:07
@MintMain21 I added the badge.

**Comment by ManeraKai** [comment] 2023-12-18 09:11
> Shouldn't we report bugs one by one in separate issues so that there is no clutter?

@opusforlife2 I'll add the label `Firefox-Android ` for them.

**Comment by ManeraKai** [comment] 2023-12-19 06:46
I'll close this issue and complete it in the other sub-issues: https://github.com/libredirect/browser_extension/issues/874, https://github.com/libredirect/browser_extension/issues/873

**Closed by ManeraKai** 2023-12-19 06:46 UTC
Labels: enhancement, Firefox-Android
