### ISSUE TITLE
Add Twineo

### ISSUE THREAD

**Issue by skynet2982** [libredirect/browser_extension#847] opened 2023-11-03 16:51 UTC
Add Twineo as Twitch alternative front-end : https://cloudyy.exozy.me/projects/twineo/

I tried to configure the extension like this.

![Screenshot 2023-11-03 at 17 50 10](https://github.com/libredirect/browser_extension/assets/7713432/70da8fb8-ddd0-4a70-a8e0-b8817a7befd3)

And it works ! So it should not be so much to add to the extension :)

**Comment by ManeraKai** [comment] 2023-11-03 17:03
Duplicate of: https://codeberg.org/LibRedirect/browser_extension/issues/103.

**Closed by ManeraKai** 2023-11-03 17:03 UTC
