### ISSUE TITLE
[Feature request]: Delete tubo (soundcloud alternative)

### ISSUE THREAD

**Issue by stemy2** [libredirect/browser_extension#972] opened 2024-08-16 14:18 UTC
Hello,

The alternative to soundcloud is not usable anymore. The only instance provided and the repository URL are broken links, so they have to be deleted from the extension.

**Comment by ManeraKai** [comment] 2024-08-19 08:37
Duplicate of: https://codeberg.org/LibRedirect/browser_extension/issues/144

**Closed by ManeraKai** 2024-08-19 08:37 UTC
